# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# Vite embeds `VITE_*` env vars at build time.
# Our `.dockerignore` excludes `.env*`, so provide these as build args in CI/CD.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_PROD_DOMAIN
ARG VITE_TENANT_DOMAIN
ARG VITE_TENANT_ROUTING
ARG VITE_DEV_TENANT_DOMAIN
ARG VITE_RECAPTCHA_SITE_KEY
ARG VITE_RECAPTCHA_FAIL_OPEN

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_PROD_DOMAIN=$VITE_PROD_DOMAIN
ENV VITE_TENANT_DOMAIN=$VITE_TENANT_DOMAIN
ENV VITE_TENANT_ROUTING=$VITE_TENANT_ROUTING
ENV VITE_DEV_TENANT_DOMAIN=$VITE_DEV_TENANT_DOMAIN
ENV VITE_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY
ENV VITE_RECAPTCHA_FAIL_OPEN=$VITE_RECAPTCHA_FAIL_OPEN

RUN npm run build

# Runtime stage
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY server.js ./
EXPOSE 8080
CMD ["node", "server.js"]
