import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Hero header */}
      <div className="border-b border-border bg-muted/30">
        <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-8 items-start">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary mb-4">
                Current as of 27 March 2026
              </p>
              <h1 className="text-3xl sm:text-4xl font-bold text-foreground">Terms of Service</h1>
            </div>
            <p className="text-muted-foreground leading-relaxed text-sm md:pt-8">
              By accessing our platform, you are agreeing to be bound by these terms of service, and agree that
              you are responsible for compliance with any applicable local laws.
            </p>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <Button variant="ghost" size="sm" className="mb-8" onClick={() => navigate(-1)}>
          <ArrowLeft className="mr-2 h-4 w-4" /> Back
        </Button>

        <div className="space-y-10 text-sm leading-relaxed">
          {/* 1. Agreement */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Agreement to Terms</h2>
            <p className="text-muted-foreground">
              These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "you", or "your")
              and HKFT Services (Pty) Ltd, trading as MyCoop Asset Management ("MyCoop", "we", "us", or "our"), governing
              your access to and use of the MyCoop Asset Management platform, including all related websites, applications,
              tools, and services (collectively, the "Platform").
            </p>
            <p className="text-muted-foreground mt-3">
              By creating an account, accessing, or using the Platform in any way, you confirm that you have read,
              understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must not
              access or use the Platform.
            </p>
            <p className="text-muted-foreground mt-3">
              These Terms are subject to and should be read in conjunction with our{" "}
              <a href="/privacy-policy" className="text-primary underline underline-offset-2">Privacy Policy</a> and{" "}
              <a href="/cookie-policy" className="text-primary underline underline-offset-2">Cookie Policy</a>.
            </p>
          </section>

          {/* 2. Definitions */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Definitions</h2>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5">
              <li><strong>"Cooperative"</strong> means a registered co-operative organisation that has subscribed to and operates on the Platform.</li>
              <li><strong>"Member"</strong> means a natural or juristic person who holds membership in a Cooperative and has an account on the Platform.</li>
              <li><strong>"Administrator"</strong> means a user authorised by a Cooperative to manage its operations, members, and data on the Platform.</li>
              <li><strong>"Pool"</strong> means a pooled investment vehicle managed by a Cooperative through the Platform.</li>
              <li><strong>"Transaction"</strong> means any deposit, withdrawal, transfer, switch, or other financial operation processed through the Platform.</li>
              <li><strong>"Content"</strong> means all text, data, documents, images, and other materials uploaded to or generated by the Platform.</li>
            </ul>
          </section>

          {/* 3. Eligibility */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. Eligibility</h2>
            <p className="text-muted-foreground">
              To use the Platform, you must:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>Be at least 18 years of age, or have the consent of a parent or legal guardian.</li>
              <li>Have the legal capacity to enter into a binding agreement.</li>
              <li>Provide accurate, current, and complete registration information.</li>
              <li>Be an authorised representative of a Cooperative (for Administrator accounts) or an approved member of a Cooperative (for Member accounts).</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              Cooperatives registering on the Platform must be duly registered under the Co-operatives Act, 2005
              (Act No. 14 of 2005) or equivalent legislation in their jurisdiction.
            </p>
          </section>

          {/* 4. Account Registration */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Account Registration and Security</h2>
            <p className="text-muted-foreground">
              You are responsible for:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>Maintaining the confidentiality of your login credentials.</li>
              <li>All activities that occur under your account.</li>
              <li>Notifying us immediately of any unauthorised use of your account.</li>
              <li>Ensuring that your registered email address is valid and accessible, as it is the primary means of account communication.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              We reserve the right to suspend or terminate accounts that we reasonably believe have been compromised
              or are being used in violation of these Terms.
            </p>
          </section>

          {/* 5. Platform Services */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Platform Services</h2>
            <p className="text-muted-foreground mb-3">
              The Platform provides cooperative management tools including, but not limited to:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5">
              <li>Member registration, onboarding, and identity verification.</li>
              <li>Entity and account management across multiple membership types.</li>
              <li>Pooled investment tracking, unit pricing, and holdings management.</li>
              <li>Financial transaction processing (deposits, withdrawals, transfers, switches).</li>
              <li>Loan application processing, repayment scheduling, and acknowledgment of debt generation.</li>
              <li>Debit order mandate management.</li>
              <li>Document management and compliance record-keeping.</li>
              <li>Statement generation, tax certificate production, and reporting.</li>
              <li>Communication tools for member notifications and campaigns.</li>
              <li>Multi-tenant administration for head office oversight.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              We reserve the right to modify, suspend, or discontinue any feature of the Platform at any time, with
              reasonable notice where practicable.
            </p>
          </section>

          {/* 6. Multi-Tenant Structure */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Multi-Tenant Structure</h2>
            <p className="text-muted-foreground">
              The Platform operates on a multi-tenant architecture where each Cooperative maintains a separate,
              isolated data environment. You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>Your data is logically segregated from other Cooperatives on the Platform.</li>
              <li>Administrators of your Cooperative have access to your membership data as required for cooperative administration.</li>
              <li>MyCoop, as the platform provider, has access to data across all tenants for the purposes of platform maintenance, support, and legal compliance.</li>
              <li>Each Cooperative is independently responsible for its own governance, investment decisions, and regulatory compliance.</li>
            </ul>
          </section>

          {/* 7. Financial Transactions */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Financial Transactions and Investments</h2>
            <p className="text-muted-foreground">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>MyCoop is a technology platform provider and does <strong>not</strong> provide financial advice, investment advice, or act as a financial services provider.</li>
              <li>All investment decisions are made by you and/or your Cooperative. MyCoop bears no responsibility for investment outcomes, returns, or losses.</li>
              <li>Pool unit prices displayed on the Platform are calculated based on data provided by Cooperatives and third-party market data providers. MyCoop does not guarantee the accuracy of pricing data.</li>
              <li>Transactions are subject to approval workflows configured by your Cooperative's administrators.</li>
              <li>Completed and approved transactions cannot be reversed through the Platform except through a new offsetting transaction or administrative correction.</li>
              <li>Debit order mandates are processed according to the instructions you provide. You are responsible for ensuring sufficient funds are available.</li>
            </ul>
          </section>

          {/* 8. Loans */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Loan Facilities</h2>
            <p className="text-muted-foreground">
              Where your Cooperative offers loan facilities through the Platform:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>Loan terms, interest rates, and conditions are determined by your Cooperative, not by MyCoop.</li>
              <li>By accepting a loan and signing an Acknowledgment of Debt electronically, you enter into a binding agreement with your Cooperative.</li>
              <li>Electronic signatures captured on the Platform are legally binding under the Electronic Communications and Transactions Act, 2002 (ECTA).</li>
              <li>Failure to maintain loan repayments may result in recovery action by your Cooperative, including deduction from your pool holdings.</li>
              <li>MyCoop facilitates the loan process but is not a party to any loan agreement between you and your Cooperative.</li>
            </ul>
          </section>

          {/* 9. User Obligations */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. User Obligations</h2>
            <p className="text-muted-foreground mb-3">When using the Platform, you agree to:</p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5">
              <li>Provide truthful, accurate, and complete information during registration and throughout your use of the Platform.</li>
              <li>Comply with all applicable South African laws, including POPIA, FICA, the Co-operatives Act, and tax legislation.</li>
              <li>Not use the Platform for any unlawful, fraudulent, or harmful purpose.</li>
              <li>Not attempt to gain unauthorised access to any part of the Platform, other user accounts, or underlying systems.</li>
              <li>Not interfere with, disrupt, or place an undue burden on the Platform or its infrastructure.</li>
              <li>Not upload malicious code, viruses, or any content that could compromise platform security.</li>
              <li>Not scrape, harvest, or extract data from the Platform by automated means without express written permission.</li>
              <li>Promptly update your information if it changes.</li>
            </ul>
          </section>

          {/* 10. Intellectual Property */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Intellectual Property</h2>
            <p className="text-muted-foreground">
              All intellectual property rights in the Platform — including its design, source code, algorithms,
              interfaces, branding, logos, and documentation — are and remain the exclusive property of MyCoop
              or its licensors.
            </p>
            <p className="text-muted-foreground mt-3">
              You are granted a limited, non-exclusive, non-transferable, revocable licence to access and use the
              Platform solely for its intended purpose. You may not copy, modify, distribute, sell, or lease any
              part of the Platform without our prior written consent.
            </p>
            <p className="text-muted-foreground mt-3">
              Content you upload to the Platform (e.g., documents, data) remains your property. By uploading
              Content, you grant MyCoop a limited licence to store, process, and display it as necessary to
              provide the Platform services.
            </p>
          </section>

          {/* 11. Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Limitation of Liability</h2>
            <p className="text-muted-foreground">
              To the maximum extent permitted by South African law:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>The Platform is provided on an "as is" and "as available" basis without warranties of any kind, whether express, implied, or statutory.</li>
              <li>MyCoop does not warrant that the Platform will be uninterrupted, error-free, secure, or free of viruses or other harmful components.</li>
              <li>MyCoop shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, business opportunities, or goodwill.</li>
              <li>MyCoop's total aggregate liability for any claims arising from or related to the Platform shall not exceed the fees paid by you or your Cooperative to MyCoop in the twelve (12) months preceding the claim.</li>
              <li>MyCoop is not liable for any losses arising from investment decisions, market fluctuations, or the financial performance of any Pool or Cooperative.</li>
              <li>MyCoop is not liable for errors in data provided by third-party market data providers or Cooperative administrators.</li>
            </ul>
          </section>

          {/* 12. Indemnification */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">12. Indemnification</h2>
            <p className="text-muted-foreground">
              You agree to indemnify, defend, and hold harmless MyCoop, its directors, officers, employees, and
              agents from and against any claims, damages, losses, liabilities, costs, and expenses (including
              legal fees) arising from or related to:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>Your use of or conduct on the Platform.</li>
              <li>Your violation of these Terms or any applicable law.</li>
              <li>Your violation of any rights of a third party.</li>
              <li>Any Content you upload or submit to the Platform.</li>
            </ul>
          </section>

          {/* 13. Termination */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">13. Termination</h2>
            <p className="text-muted-foreground">
              We may suspend or terminate your access to the Platform at any time, with or without cause, and with
              or without notice, including but not limited to situations where:
            </p>
            <ul className="list-disc pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>You breach these Terms.</li>
              <li>Your Cooperative's subscription is terminated or suspended.</li>
              <li>We are required to do so by law or regulatory order.</li>
              <li>We reasonably believe your account poses a security risk.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              Upon termination, your right to access the Platform ceases immediately. Provisions that by their
              nature should survive termination — including intellectual property, limitation of liability,
              indemnification, and dispute resolution — shall continue in effect.
            </p>
            <p className="text-muted-foreground mt-3">
              Data retention following termination is governed by our{" "}
              <a href="/privacy-policy" className="text-primary underline underline-offset-2">Privacy Policy</a> and
              applicable legal retention requirements.
            </p>
          </section>

          {/* 14. Dispute Resolution */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">14. Dispute Resolution</h2>
            <p className="text-muted-foreground">
              Any dispute arising from or in connection with these Terms shall be:
            </p>
            <ol className="list-decimal pl-5 text-muted-foreground space-y-1.5 mt-2">
              <li>First attempted to be resolved through good-faith negotiation between the parties within 30 days of written notice of the dispute.</li>
              <li>If not resolved through negotiation, submitted to mediation under the rules of the Arbitration Foundation of Southern Africa (AFSA).</li>
              <li>If mediation fails, submitted to binding arbitration under AFSA rules. The arbitration shall take place in Johannesburg, South Africa, and shall be conducted in English.</li>
            </ol>
            <p className="text-muted-foreground mt-3">
              Nothing in this clause prevents either party from seeking urgent interim relief from a court of competent jurisdiction.
            </p>
          </section>

          {/* 15. Governing Law */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">15. Governing Law and Jurisdiction</h2>
            <p className="text-muted-foreground">
              These Terms are governed by and construed in accordance with the laws of the Republic of South Africa.
              Subject to the dispute resolution clause above, you consent to the exclusive jurisdiction of the
              High Court of South Africa, Gauteng Division, Johannesburg.
            </p>
          </section>

          {/* 16. Severability */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">16. Severability</h2>
            <p className="text-muted-foreground">
              If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of
              competent jurisdiction, the remaining provisions shall continue in full force and effect. The invalid
              provision shall be modified to the minimum extent necessary to make it valid and enforceable.
            </p>
          </section>

          {/* 17. Entire Agreement */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">17. Entire Agreement</h2>
            <p className="text-muted-foreground">
              These Terms, together with our Privacy Policy and Cookie Policy, constitute the entire agreement
              between you and MyCoop regarding your use of the Platform, and supersede all prior agreements,
              understandings, and representations.
            </p>
          </section>

          {/* 18. Changes */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">18. Changes to These Terms</h2>
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms at any time. When we make material changes, we will
              update the "Current as of" date at the top of this page and, where appropriate, notify you via
              the Platform or email. Your continued use of the Platform after changes are posted constitutes
              acceptance of the modified Terms.
            </p>
          </section>

          {/* 19. Contact */}
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">19. Contact Us</h2>
            <p className="text-muted-foreground">
              For questions or concerns about these Terms, please contact us:
            </p>
            <div className="mt-3 rounded-lg border border-border bg-muted/30 p-4 text-muted-foreground">
              <p><strong className="text-foreground">HKFT Services (Pty) Ltd</strong></p>
              <p>Trading as MyCoop Asset Management</p>
              <p>Email: <a href="mailto:legal@myco-op.co.za" className="text-primary underline underline-offset-2">legal@myco-op.co.za</a></p>
              <p>General: <a href="mailto:info@myco-op.co.za" className="text-primary underline underline-offset-2">info@myco-op.co.za</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
